### PR TITLE
Configurable Icon Rendering

### PR DESCRIPTION
**Pull request by ralouphie**
Hello, firstly thank you for the fantastic library! I decided to PR this change to add the ability to customize icon rendering.

This allows easy usage with the new [official Font Awesome React library](https://github.com/FortAwesome/react-fontawesome). Also allows changing icons to use any custom rendering desired.

I've added a storybook story that uses emojis as icons as an example:

screen shot 2018-06-29 at 1 51 58 pm

Here's a snippet of the changes from the updated readme:

> By default, React-mde will use Font Awesome class names to render icons (see above for how to install).
> The default icon provider returns icons that look like the following:

> ```jsx
> <i className={`fas fa-${icon}`} aria-hidden="true"/>
> ```
>
> This can be changed by passing a `buttonContentOptions` prop to the `ReactMde` component with an `iconProvider` option to tell React-mde how to render icons.
>
> For example, you can use your own custom icon component by changing the `iconProvider`:
>
> ```jsx
> <ReactMde
>     buttonContentOptions={{
>         iconProvider: name => <MyCustomIcon name={name} />,
>     }}
>     onChange={this.handleValueChange}
>     // ...
> />

Summary of changes:

- Update `Command` to take a builder for
  button content (`buttonContentBuilder`)
  instead of the content directly (`buttonContent`)
- Pass new `ButtonContentOptions` type to `buttonContentBuilder`
  containing the `iconProvider`.
- Update all commands to use the `iconProvider`
  instead of the `MdeToolbarIcon` component directly.
- Add `buttonContentOptions` prop to `ReactMde`.
- Propagate `buttonContentOptions` down
  to where command buttons are rendered.
- Add new story to storybook with example emoji rendering for icons.

### CODE REVIEW

**Comment by AndreasVolkmann** [comment]
This is pretty great indeed! Thanks a lot.

**Comment by AndreasVolkmann** [comment]
Only comment: I tried using this with the fontawesome react library. The icons have a very small clickable area. Do you have similar experiences?

**Comment by ralouphie** [comment]
@AndreasVolkmann No problem :) I'm actually using this with the fontawesome react library as well. Not seeing that issue though. The buttons seem to be around 19x22 depending on the icon since they're different widths:

screen shot 2018-07-03 at 12 09 24 pm

Should be easy to give the icons a minimum width using CSS:

```
li.mde-header-item > button > svg {
  min-width: 19px;
}
```

**Comment by AndreasVolkmann** [comment]
@ralouphie thanks for the reply. 

Seems my problem was a different one. 
As you can see in the picture, the button is somehow misaligned. 

I am using firefox, but just tried the same in chrome and there the whole icon is clickable, even though the button still seems to be off. 

image

**Pull request merged**
