### PR TITLE
option to show the preview pane on the side

### PR DESCRIPTION
**Pull request by xdamman**
Added a new `className` prop that can be used to add a custom class or to use the class `column`

### CODE REVIEW

**Comment by andrerpena** [comment]
@xdamman , thank you very much for your contribution. I need this night (CET) to review the changes and push it to NPM.
Thanks again.

**Comment by xdamman** [comment]
Oh cool, that was fast to merge, I won't need this anymore: https://github.com/opencollective/frontend/blob/updates/package.json#L81 😊
Thank you for your great work! 🙏 (btw, happy to contribute if you create an open collective for this, see https://opencollective.com/opensource)

**Comment by travisdmathis** [comment]
When do you think this will be deployed to NPM? I could really use this update in a project i'm working on 🙏 thanks for your hard work @xdamman and @andrerpena

**Comment by andrerpena** [comment]
First, @xdamman, I appreciate your effort but unfortunately I had to rollback your changes except for the addition of the `className` prop because your implementation was not production ready.

Example:

image

So, since people like you and @travisdmathis are in need of this feature, I've created #73 and I'll start working on an implementation like Github, using tabs. So you'll be able to choose Stackoverflow style (vertical) or Github style (horizontal with tabs).

About https://opencollective.com, thanks for your support, I didn't even know about it.  I think I'll wait until RMDE is a bit more mature and popular :)

@travisdmathis, I think you'll have to wait until the side-preview is production ready, sorry.

**Comment by travisdmathis** [comment]
@andrerpena no problem, if there's anything I can do to help, point me in the right direction.  Thanks again for the work put into this project.

**Comment by andrerpena** [comment]
@travisdmathis Thank you very much! I'll think of a good architecture, put something together on a feature-branch and ping you. If you want to help, I'd appreciate, otherwise, don't worries.

Thanks again.

**Comment by xdamman** [comment]
No worries.

Sorry didn’t think of handling that case.
What about just auto expanding the text area?

Tabs are nice but as far as I’m concerned I like columns better so that you have direct feedback/preview.

**Comment by travisdmathis** [comment]
I suggest having it collapse bellow on mobile devices.. that's what I intended to do w/ columns..

**Comment by andrerpena** [comment]
@xdamman and @travisdmathis, I'll move the discussion to https://github.com/andrerpena/react-mde/issues/73 so it's then visible to everyone. I'll ping you there, thanks.

**Pull request merged**
