### PR TITLE
Drag&drop plus select with dialog (ala github) for image uploads

### PR DESCRIPTION
**Pull request by jacargentina**
@andrerpena can you take a look? Hope this can be merged soon, so if you see any changes needed to make it better, I'm fresh with ts and the code right now!

**Update**: also added banner below the textArea, with input to select images via input, ala GitHub!!

Captura de Pantalla 2020-08-13 a la(s) 22 13 17

### CODE REVIEW

**Comment by andrerpena** [comment]
Thank you very much. Amazing. This looks promising. I will review shortly!

**Comment by andrerpena** [comment]
@jacargentina thanks again for this. Really well done.

tomorrow night I will fix some rough edges before pushing to NPM:

- [ ] Add the text `Attach files by dragging...` to the l18n file so it can be translated
- [ ] Add `user-select: none` to the `Attach files by dragging...` span so the text will not select when you move up and down the resize grip
- [ ] Change the resize grip to be like Github, instead of Stackoverflow.. (nice to have)

image

I promise I will release some version tomorrow.. If I am unable to do all these things in one go, I will either release anyway without the last one.. or at least release a pre-release version.

Thank you again for pushing this.

**Comment by jacargentina** [comment]
@andrerpena I can do the first 2 things if u like? They are pretty easy.

**Comment by andrerpena** [comment]
That would be lovely =)

**Comment by andrerpena** [comment]
I published this under the `next` tag unti I finalize some tests. Code sandbox https://codesandbox.io/s/react-typescript-forked-psjcd

**Comment by rashil2000** [comment]
@andrerpena I'd like to know how to handle the `data` parameter that's being passed as `ArrayBuffer` in the SaveImageHandler. The StackOverflow link you provided in the demo above works only for .png images and that too in PHP. Ideally, I'd like to know the filename and filetype of the image being pasted too (since the output text depends on it), and would like to use FormData() in JavaScript Fetch. I tried looking everywhere but couldn't find anything :(

Thanks in advance!!

**Pull request merged**
