### PR TITLE
Adding Tabbed layout

### PR DESCRIPTION
**Pull request by Nes-si**

### CODE REVIEW

**Comment by andrerpena** [comment]
I'm really thankful for your great contributions.. I'm still playing around and checking the changes.. That's why I didn't comment or push it to NPM yet 👍

**Comment by Nes-si** [comment]
You're welcome.

**Comment by andrerpena** [comment]
@Nes-si The vertical layout seems broken now:

image

**Comment by Nes-si** [comment]
But... what wrong with it?

**Comment by andrerpena** [comment]
@Nes-si  Ah.. It's that it wasn't obvious to me that those were toggable buttons.. Maybe adding a checkbox will make it more obvious. I think its cleaner if the vertical layout doesnt have this option.. Because we already have the no-preview layout, but I'm OK with these buttons as long as it is obvious that they are toggable.

**Comment by Nes-si** [comment]
@andrerpena you're right. I'm not UI designer, it's a draft.
I think, no preview layout is for projects where Markdown-preview is a separate component.

**Comment by andrerpena** [comment]
@Nes-si It makes sense. I'll focus now on adjusting the UI for the final 5.5 release. Your new PRs have been merged and published as 5.5.0-alpha.2.

Thanks again ❤️

**Pull request merged**
