### PR TITLE
Custom Button Option [New Feature, no Breaking Changes]

### PR DESCRIPTION
**Pull request by bnbarak**
@andrerpena, thank you for maintaining this great component. 

## Intro
The team at [comet.ml](comet.ml) liked your component and we think it has some nice clean code and behavior. We also needed an upload option and a little more flexibility to meet all of our requirements. So we took the time to add this custom button feature. This is not a break change.

## What
The ability to render a custom component in a command. In order to make it a useful feature and full duplex, the user also need to be able to pass value(s) to the excuse function.
custom_button

## How
1. Change the `MdeToolbarButton` to [render a custom component](https://github.com/andrerpena/react-mde/pull/121/files#diff-8f635e37744d213c5495a30c437f7a96R27) from props if one exists:
```
const {buttonContent, buttonProps, onClick, readOnly, CustomButtonComponent, setValues} = props;
    const defaultButton = (
        <button
            type="button"
            {...buttonProps}
            onClick={onClick}
            disabled={readOnly}
        >
            {buttonContent}
        </button>
    );
    const customComponent = (<CustomButtonComponent handleSubmit={onClick} setValues={setValues}/>);
    return (
        <li className="mde-header-item">
            {CustomButtonComponent ? customComponent : defaultButton}
        </li>
    );
```
2. Expose [two function](https://github.com/andrerpena/react-mde/pull/121/files#diff-8f635e37744d213c5495a30c437f7a96R24) in the props in `MdeToolbar`:
```
CustomButtonComponent={c.CustomButtonComponent}
setValues={c.setValues}
```

3. Command now looks like:
```
const customCommand: Command = {
    buttonContentBuilder: ({ iconProvider }) => iconProvider("bold"),
    execute: (state) => {
       
    },
    CustomButtonComponent: ButtonComponent,
    setValues: (value) => {
        myVal = value;
    },
};
```

4. `ButtonComponent` can invoke `this.props.handleSubmit` and `this.props.setValues`

## Notes
This is my (@bnbarak) first time writing in TypeScript - please excuse my mistakes and let me know of any rejections. 

We hope you accept our changes,
Barak

## Example
See [storybook](https://github.com/bnbarak/react-mde/blob/c9958fece918deea91ca2d5a11205752da1dd7ff/.storybook/stories/button/CustomButtonStory.tsx) example.

### CODE REVIEW

**Comment by andrerpena** [comment]
Hey @bnbarak. Thank you very much for your PR. It sounds interesting. I'm super glad to hear that https://www.comet.ml/ is using React-Mde. I'll merge your PR now, review it this night (I didn't have time this weekend) and then I'll push it to NPM this night.

Thank you very much again.

**Comment by andrerpena** [comment]
I'm restructuring the Storybook. I'm creating a `Customization` section and putting `Command Icons` and `Command Button` inside it.

**Comment by andrerpena** [comment]
What you actually wanted to do is not to pass a `CustomButtonComponent`. What you wanted to do was to change `button` to something else. We cannot have a `CustomButtonComponent` with specific properties like `handleSubmit` and `setValues`. If you want to pass `props` to the button, there was already a `buttonProps`. What was impossible to do before was to change the `button` component. 

image

I will change the code accordingly.

**Comment by andrerpena** [comment]
Unfortunately I had to temporarily "revert" the changes because I don't have time to work on it anymore today (https://github.com/andrerpena/react-mde/commit/07e3ae0889df3aae816ddacfdefae674d3d250d6)

**Comment by humont** [comment]
hi @andrerpena , is this PR still being worked on?

or is there another way to define a custom button to create custom behaviours on click?

Thanks for the great module btw!

**Pull request merged**
