### PR TITLE
WIP: Mentions support

### LINKED ISSUE #200: Mentions support
Hi @andrerpena! I noticed you opened an issue two years ago about adding mentions support:

https://github.com/andrerpena/react-mde/issues/14

However, looking at the README, I'm not sure how to setup mentions with React MDE. I'd like the mentions to look the way they do on GitHub.

Any pointers?

### PR DESCRIPTION
**Pull request by andrerpena**
Fixes #200

I probably need 10 more days to finish this and test it

### CODE REVIEW

**Comment by veeral-patel** [comment]
@andrerpena Thanks for working on this feature, I'm really looking forward to it!

Any idea when it'll be ready to use?

**Comment by andrerpena** [comment]
@veeral-patel probably one more week. This will be a Christmas feature 🎅

**Comment by veeral-patel** [comment]
@andrerpena Got it, looking forward to it!

**Comment by andrerpena** [comment]
@veeral-patel enjoy!

**Pull request closed without merging**
