### PR TITLE
Implements #208: full screen/page for better documentation authoring

### PR DESCRIPTION
**Pull request by jacargentina**
Adds a "full screen" button to allow customizing the editor to make it full screen; adds an `onMaximizeChange` event to allow the libray user code to modify the container, etc.

ScreenFlow

### CODE REVIEW

**Comment by jacargentina** [comment]
@andrerpena I would love to complete the README.md docs if this is accepted

**Comment by andrerpena** [comment]
Hey @jacargentina. Thanks for this. 
The hardest part of open-source is to sometimes have to reject PRs.
Unfortunately, since the Github editor does not have this feature, I feel like I should not accept it, because people have different requirements and if I accept all PRs, the library will become unmaintainable. I have tried before =/
 Thanks again for all your contributions.

**Comment by jacargentina** [comment]
@andrerpena i don't have any problem on a PR being rejected, but the bad feeling is having to for non-technical reasons! 😔

1. Why should react-me only have features which GitHub have? Why can't it be maybe .... better? Or at least, in some aspects for very specific use cases, which GitHub editor is not for (ie. just commenting in issues, PRs, etc, for source code project)
2. I've simply tried to help because on #208 you said it can be included, maybe you changed your mind? Again, would be nice to have another better (at least for me) technical reason.
3. I can always fork and publish my own react-mde version, but in case of open source project, I first always prefer try to keep it **upstream**. 

Cheers!

**Comment by andrerpena** [comment]
Hey @jacargentina I am really sorry again.

1. Because I decided to trust that Github did necessary user research and technical analysis to conclude that the editor should be exactly like this. At least by not adding more, I am not risking falling into a trap I am not seeing, and not risking maintaining a feature that does not have a lot of demand. For example. If we add this maximize feature, there is a chance that someone, on a specific use case, will come back here complaining about a bug. Every time you add a feature, you are deciding to maintain that forever.
1. I am sorry about #208. When I said it was a good idea, I was referring to disabling the height grip.
1. You can always fork this, and if you do, I am still grateful for your valuable contributions. What I would be more willing to do, is to find a way to enable the maximize button to be a command that can be added externally... in a generic way. In such a way that you can have the functionality without it being inside the core editor

Thank you again

**Pull request closed without merging**
